services:
  keycloak-token-status-plugin:
    image: quay.io/keycloak/keycloak:26.4.5
    command: >
      start-dev --features=oid4vc-vci --log-level=INFO,com.adorsys.keycloakstatuslist:DEBUG
      --db=postgres --db-username=admin --db-password=admin
      --db-url=jdbc:postgresql://host.docker.internal:5432/keycloak_token_status
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8090:8080"
    volumes:
      - ./target/keycloak-token-status-plugin-1.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-token-status-plugin-1.0.0-SNAPSHOT.jar
